import 'package:flutter/material.dart';
import '../utils/app_styles.dart';
import '../widgets/wave_background.dart';
import 'payment_success_screen.dart';

class CarDetailsScreen extends StatelessWidget {
  final Map<String, dynamic> car;

  const CarDetailsScreen({super.key, required this.car});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          // الجزء العلوي مع الخلفية المموجة
          Container(
            height: 200,
            child: Stack(
              children: [
                const WaveBackground(),
                SafeArea(
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Row(
                      children: [
                        IconButton(
                          onPressed: () => Navigator.pop(context),
                          icon: const Icon(
                            Icons.arrow_back,
                            color: AppColors.white,
                          ),
                        ),
                        Expanded(
                          child: Text(
                            car['name'],
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              color: AppColors.white,
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                        const SizedBox(width: 48),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
          // محتوى التفاصيل
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // صورة السيارة
                  Container(
                    height: 200,
                    width: double.infinity,
                    decoration: BoxDecoration(
                      color: AppColors.lightGray,
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(16),
                      child: Image.asset(
                        car['image'],
                        fit: BoxFit.contain,
                        errorBuilder: (context, error, stackTrace) {
                          return const Icon(
                            Icons.directions_car,
                            size: 80,
                            color: AppColors.primaryBlue,
                          );
                        },
                      ),
                    ),
                  ),
                  const SizedBox(height: 20),
                  // اسم السيارة والسعر
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        car['name'],
                        style: AppTextStyles.heading1,
                      ),
                      Text(
                        car['price'],
                        style: AppTextStyles.heading2.copyWith(
                          color: AppColors.primaryBlue,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 10),
                  // التقييم
                  Row(
                    children: [
                      const Icon(Icons.star, color: AppColors.orange, size: 20),
                      const SizedBox(width: 4),
                      Text(
                        car['rating'].toString(),
                        style: AppTextStyles.bodyText,
                      ),
                    ],
                  ),
                  const SizedBox(height: 20),
                  // الوصف
                  const Text(
                    'This text is an example of text that can be replaced in the same space. It was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application.',
                    style: AppTextStyles.bodyText,
                    textAlign: TextAlign.right,
                  ),
                  const SizedBox(height: 20),
                  // الميزات
                  const Text(
                    'Features:',
                    style: AppTextStyles.heading2,
                  ),
                  const SizedBox(height: 10),
                  Wrap(
                    spacing: 8,
                    runSpacing: 8,
                    children: (car['features'] as List<String>).map((feature) {
                      return Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 12,
                          vertical: 6,
                        ),
                        decoration: BoxDecoration(
                          color: AppColors.lightBlue.withOpacity(0.2),
                          borderRadius: BorderRadius.circular(20),
                          border: Border.all(
                            color: AppColors.lightBlue,
                            width: 1,
                          ),
                        ),
                        child: Text(
                          feature,
                          style: AppTextStyles.caption.copyWith(
                            color: AppColors.primaryBlue,
                          ),
                        ),
                      );
                    }).toList(),
                  ),
                  const SizedBox(height: 20),
                  // معلومات إضافية
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: AppColors.lightGray.withOpacity(0.5),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Column(
                      children: [
                        _buildInfoRow('Transmission', car['transmission']),
                        const Divider(),
                        _buildInfoRow('Fuel Type', car['fuel']),
                        const Divider(),
                        _buildInfoRow('Year of manufacture', car['year']),
                      ],
                    ),
                  ),
                  const SizedBox(height: 30),
                  // زر الحجز
                  SizedBox(
                    width: double.infinity,
                    height: 50,
                    child: ElevatedButton(
                      onPressed: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => const PaymentSuccessScreen(),
                          ),
                        );
                      },
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primaryBlue,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(25),
                        ),
                        elevation: 5,
                      ),
                      child: const Text(
                        'Book now',
                        style: AppTextStyles.buttonText,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInfoRow(String label, String value) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(label, style: AppTextStyles.bodyText),
        Text(
          value,
          style: AppTextStyles.bodyText.copyWith(
            fontWeight: FontWeight.w600,
          ),
        ),
      ],
    );
  }
}

